### ISSUE TITLE
Tracking quality / tracking callback 

### ISSUE THREAD

**Issue by yosun** [8thwall/xr-unity#33]
Is there a way to get tracking quality, such as number of feature points detected?

Also, is there some sort of callback when tracking is lost/detected

**Comment by D3m0n92** [comment]
Yeah! Same identical perplexities. The callbacks are then mandatory.

**Comment by D3m0n92** [comment]
@erikmchut any news for the callback? Are very important.

**Comment by atomarch** [comment]
Hello @D3m0n92 @yosun , A new tracking quality API (XRTrackingState) has been added in R6.  

Documentation here:
https://docs.8thwall.com/#xrtrackingstate

**Comment by erikmchut** [comment]
@D3m0n92 @yosun 
With the new tracking quality API, you can query the tracking state in each run loop iteration, for example, from within the Update() method of a GameObject.

We've designed it so that it would be easy to create a wrapped callback API through a coroutine if you'd prefer, and we'd be happy to consider that as a user-contribution in the [/scripts](https://github.com/8thwall/xr-unity/tree/master/scripts) directory.
